Repository pyapp-kit/psygnal, pull requests merged in 2021-11, with the labels that each got.

#31 add asv benchmark to CI
  .github/workflows/benchmark.yml
  .gitignore
  asv.conf.json
  benchmarks/__init__.py
  benchmarks/benchmarks.py
Labels: run-benchmark

#32 Change benchmark publication approach
  .asv/results/GitHubRunner/057d0e82-conda-py3.9-cython.json
  .asv/results/GitHubRunner/057d0e82-conda-py3.9.json
  .asv/results/GitHubRunner/407f40a8-conda-py3.9-cython.json
  .asv/results/GitHubRunner/407f40a8-conda-py3.9.json
  .asv/results/GitHubRunner/adc34f08-conda-py3.9-cython.json
  .asv/results/GitHubRunner/adc34f08-conda-py3.9.json
  .asv/results/GitHubRunner/b1f41733-conda-py3.9-cython.json
  .asv/results/GitHubRunner/b1f41733-conda-py3.9.json
  .asv/results/GitHubRunner/machine.json
  .asv/results/benchmarks.json
  .github/workflows/benchmark.yml
  .gitignore
Labels: run-benchmark

#28 Set SignalInstances directly as attributes on objects (fix bug with hashable signal holders)
  Makefile
  psygnal/_signal.py
  tests/test_psygnal.py
Labels: bug

#33 enable uncompiled import with PSYGNAL_UNCOMPILED env var
  README.md
  psygnal/__init__.py
  psygnal/_signal.py
  setup.py
  tests/test_psygnal.py
Labels: enhancement

#34 Fix codecov CI and bring coverage back to 100
  .github/workflows/ci.yml
  MANIFEST.in
  README.md
  codecov.yml
  psygnal/__init__.py
  setup.cfg
Labels: tests

#29 Avoid holding strong reference to decorated and partial methods
  .gitignore
  Makefile
  psygnal/_signal.py
  tests/test_psygnal.py
Labels: enhancement
