Repository pyapp-kit/psygnal, pull requests merged in 2024-02, with the labels that each got.

#257 feat: emit the old value as second argument in Signals from SignalGroupDescriptor (evented dataclass)
  src/psygnal/_group_descriptor.py
  tests/test_bench.py
  tests/test_evented_decorator.py
  tests/test_group_descriptor.py
Labels: enhancement

#275 perf: Fixing performance of evented set
  benchmarks/benchmarks.py
  src/psygnal/_signal.py
  src/psygnal/containers/_evented_set.py
  tests/test_psygnal.py
Labels: enhancement

#279 feat: deduplicate events emision in nested properties
  src/psygnal/_evented_model_utils.py
  src/psygnal/_evented_model_v1.py
  src/psygnal/_evented_model_v2.py
  tests/test_evented_model.py
Labels: bug

#280 refactor: Unify pydantic evented model modules
  asv.conf.json
  benchmarks/benchmarks.py
  pyproject.toml
  src/psygnal/__init__.py
  src/psygnal/_evented_model.py
  src/psygnal/_evented_model_utils.py
  src/psygnal/_evented_model_v2.py
  src/psygnal/_pyinstaller_util/hook-psygnal.py
  tests/test_evented_model.py
Labels: refactor

#283 feat: support for evented containers as pydantic v2 fields
  src/psygnal/containers/_evented_dict.py
  src/psygnal/containers/_evented_list.py
  src/psygnal/containers/_evented_set.py
  tests/test_pydantic_support.py
Labels: enhancement

#284 test: test for recursion error
  src/psygnal/_signal.py
  tests/test_psygnal.py
  tests/test_weak_callable.py
Labels: tests
